#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'kiip'
begin
  Kiip::Cli.start(ARGV)
rescue StandardError => e
  require 'highline'
  HighLine.color_scheme = HighLine::SampleColorScheme.new
  HighLine.new.say HighLine.color(e.message, :error)
end
